mecip/urls.py
from django.urls import path
from mecip import views

app_name = 'mecip'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),


    # Criar Campus
    path('campus/<int:campus_id>/', views.campus, name='campus'),
    path('campus/create/', views.create, name='create'),
    path('campus/<int:campus_id>/update', views.update, name='update'),

    # Criar Curso
    path('curso/', views.index_course, name='index_course'),
    path('curso/<int:course_id>/', views.course, name='course'),
    path('curso/create/', views.create_course, name='create_course'),
    path('curso/<int:course_id>/update', views.update_course, name='update_course'),

    # Criar Tipo Curso
    path('tipo/', views.index_type_course, name='index_type'),
    path('tipo/<int:type_course_id>/', views.type_course, name='type_course'),
    path('tipo/criar/', views.create_type_course, name='create_type'),
    path('tipo/<int:type_course_id>/editar', views.update_type_course, name='update_type'),

    #usercreation
    path('user/register/', views.register, name='register'),
    path('user/logout/', views.logout_view, name='logout'),

    # Criar Relatório
    path('relatorio/', views.index_report, name='index_report'),
    path('relatorio/<int:report_id>/', views.report, name='report'),
    path('relatorio/criar', views.create_report, name='create_report'),
    path('curso/<int:course_id>/<int:campus_id>/criar/relatorio', views.create_report_params, name='create_report_params'),
    path('relatorio/<int:report_id>/editar', views.update_report, name='update_report'),


]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mecip.urls')),
    path('admin/', admin.site.urls),
]

mecip/views/campus_form.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ValidationError
from mecip.forms import CampusForm
from django.urls import reverse
from mecip.models import Campus
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages

def is_admin(user):
    return user.is_superuser

@user_passes_test(is_admin)
def create(request):
    form_action = reverse('mecip:create')

    if request.method == 'POST':
        form = CampusForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action,
            'site_title': 'Criar Campus',
        }

        if form.is_valid():
            campus = form.save()
            messages.success(request, 'Campus inserido com sucesso!')
            return redirect('mecip:update', campus_id= campus.pk)
        
        else:
            messages.success(request, 'Erro ao inserir Campus')


        return render(
            request,
            'mecip/create.html',
            context
        )

    context = {
        'form': CampusForm(),
        'form_action': form_action,
        'site_title': 'Criar Campus',
    }
    return render(
        request,
        'mecip/create.html',
        context
    )


@user_passes_test(is_admin)
def update(request, campus_id):
    campus = get_object_or_404(Campus, pk= campus_id)
    form_action = reverse('mecip:update', args=(campus_id,))

    if request.method == 'POST':
        form = CampusForm(request.POST, instance=campus)

        context = {
            'form': form,
            'form_action': form_action,
            'site_title': 'Editar Campus',
        }

        if form.is_valid():
            campus = form.save()
            messages.success(request, 'Campus alterado com sucesso!')
            return redirect('mecip:update', campus_id)
        
        else:
            messages.error(request, 'Erro ao alterar Campus')



        return render(
            request,
            'mecip/create.html',
            context
        )

    context = {
        'form': CampusForm(instance=campus),
        'form_action': form_action,
        'site_title': 'Editar Campus',
    }
    return render(
        request,
        'mecip/create.html',
        context
    )

mecip/views/campus_view.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from mecip.models import Campus


def index(request):
    campus = Campus.objects \
        .order_by('-id')
    paginator = Paginator(campus, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Campus'
    }

    return render(
        request,
        'mecip/index.html',
        context,
    )

def campus(request, campus_id):

    single_campus = get_object_or_404(
        Campus, pk=campus_id,
    )

    site_title = f'IFSP - {single_campus.city}'

    context = {
        'campus': single_campus,
        'site_title': site_title
    }

    return render(
        request,
        'mecip/campus.html',
        context,
    )

mecip/views/course_form.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ValidationError
from mecip.forms import CampusForm, CourseForm
from django.urls import reverse
from mecip.models import Campus, Curso
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages

def is_admin(user):
    return user.is_superuser

@user_passes_test(is_admin)
def create_course(request):
    form_action = reverse('mecip:create_course')

    if request.method == 'POST':
        form = CourseForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action,
            'site_title': 'Criar Curso'
        }

        if form.is_valid():
            course = form.save()
            messages.success(request, 'Curso cadastrado com sucesso')
            return redirect('mecip:update_course', course_id= course.pk)
        
        else:
            messages.error(request, 'Erro ao cadastrar curso')


        return render(
            request,
            'mecip/create.html',
            context
        )

    context = {
        'form': CourseForm(),
        'form_action': form_action,
        'site_title': 'Criar Curso'
    }
    return render(
        request,
        'mecip/create.html',
        context
    )

@user_passes_test(is_admin)
def update_course(request, course_id):
    course = get_object_or_404(Curso, pk= course_id)
    form_action = reverse('mecip:update_course', args=(course_id,))

    if request.method == 'POST':
        form = CourseForm(request.POST, instance=course)

        

        if form.is_valid():
            form.save()
            messages.success(request, 'Curso alterado com sucesso')
            return redirect('mecip:update_course', course_id=course.id)

        else:
            messages.error(request, 'Erro ao alterar Curso')
            context = {
            'form': form,
            'form_action': form_action,
            'site_title': 'Editar Curso',
            }


            return render(
                request,
                'mecip/create.html',
                context
            )

    form = CourseForm(instance=course)
    context = {
        'form': form,
        'form_action': form_action,
        'site_title': 'Editar Curso',
    }
    return render(request, 'mecip/create.html', context)

mecip/views/course_view.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from mecip.models import Curso

def index_course(request):
    course = Curso.objects \
        .order_by('-id')
    paginator = Paginator(course, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Cursos'
    }

    return render(
        request,
        'mecip/index_course.html',
        context,
    )

def course(request, course_id):

    single_course = get_object_or_404(
        Curso, pk=course_id,
    )
    report = single_course.relatorios.first()


    context = {
        'course': single_course,
        'report': report,
        'site_title': f'Curso - {single_course.type_course}',
    }

    return render(
        request,
        'mecip/course.html',
        context,
    )

mecip/views/report_form.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ValidationError
from mecip.forms import ReportForm
from django.urls import reverse
from mecip.models import Relatorio, Curso, Campus
from django.contrib import messages

# from django.contrib.auth.decorators import user_passes_test

def create_report(request):
    form_action = reverse('mecip:create_report')

    if request.method == 'POST':
        form = ReportForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action,
            'site_title': 'Criar Relatorio',
        }

        if form.is_valid():
            course = form.cleaned_data['course']
            campus = form.cleaned_data['campus']

            curso_exists = Curso.objects.filter(type_course=course.type_course, campus=campus).exists()

            if not curso_exists:
                messages.error(request, 'Curso não disponível nesse Campus')
            else:
                if Relatorio.objects.filter(course=course, campus=campus).exists():
                    messages.error(request, 'Já existe um relatório para este curso neste campus.')
                else:
                    report = form.save()
                    messages.success(request, 'Relatório criado com sucesso!')
                    return redirect('mecip:update_report', report_id=report.pk)
            
        return render(
            request,
            'mecip/create.html',
            context
        )

    context = {
        'form': ReportForm(),
        'form_action': form_action,
        'site_title': 'Criar Relatorio',
    }
    return render(
        request,
        'mecip/create.html',
        context
    )

def create_report_params(request, course_id, campus_id):
    course = get_object_or_404(Curso, pk=course_id)
    campus = get_object_or_404(Campus, pk=campus_id)
    form_action = reverse('mecip:create_report_params', args=[course_id, campus_id])

    if request.method == 'POST':
        form = ReportForm(request.POST)

        if form.is_valid():
            report = form.save(commit=False)
            if report.course != course or report.campus != campus:
                messages.error(request, "Não é possível criar o relatório")
            
            else:
                report.course = course  
                report.campus = campus
                report.save()
                messages.success(request, "Relatório criado com sucesso!")
                return redirect('mecip:update_report', report_id=report.pk)
    else:
        initial_data = {'course': course, 'campus': course.campus}
        form = ReportForm(initial=initial_data)

    context = {
        'form': form,
        'form_action': form_action,
        'site_title': 'Criar Relatório',
    }
    return render(request, 'mecip/create.html', context)


def update_report(request, report_id):
    report = get_object_or_404(Relatorio, pk= report_id)
    form_action = reverse('mecip:update_report', args=(report_id,))

    if request.method == 'POST':
        form = ReportForm(request.POST, instance=report)

        

        if form.is_valid():
            form.save()
            messages.success(request, 'Relatório alterado com sucesso!')

            return redirect('mecip:update_report', report_id=report.id)

        else:
            messages.error(request, 'Erro ao alterar o relatório. Já existe um relatório para o curso e campus.')

            context = {
            'form': form,
            'form_action': form_action,
            'site_title': 'Editar Relatorio',
            }


            return render(
                request,
                'mecip/create.html',
                context
            )

    form = ReportForm(instance=report)
    context = {
        'form': form,
        'form_action': form_action,
        'site_title': 'Editar Relatorio',
    }
    return render(request, 'mecip/create.html', context)

mecip/views/report_view.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from mecip.models import Relatorio

def index_report(request):
    report = Relatorio.objects \
        .order_by('-id')
    paginator = Paginator(report, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Relatorios'
    }

    return render(
        request,
        'mecip/index_report.html',
        context,
    )


def report(request, report_id):

    single_report = get_object_or_404(
        Relatorio, pk=report_id,
    )


    context = {
        'report': single_report,
        'site_title': f'Relatorio - {single_report.course}'
    }

    return render(
        request,
        'mecip/report.html',
        context,
    )

mecip/views/type_course_form.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ValidationError
from mecip.forms import TypeCourseForm
from django.urls import reverse
from mecip.models import Type_Course
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages

def is_admin(user):
    return user.is_superuser

@user_passes_test(is_admin)
def create_type_course(request):
    form_action = reverse('mecip:create_type')

    if request.method == 'POST':
        form = TypeCourseForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action,
            'site_title': 'Criar Tipo de Curso'
        }

        if form.is_valid():
            type_course = form.save()
            messages.success(request, 'Curso cadastrado com sucesso')
            return redirect('mecip:update_type', type_course_id= type_course.pk)
        
        else:
            messages.error(request, 'Erro ao cadastrar curso')


        return render(
            request,
            'mecip/create.html',
            context
        )

    context = {
        'form': TypeCourseForm(),
        'form_action': form_action,
        'site_title': 'Criar Tipo de Curso'
    }
    return render(
        request,
        'mecip/create.html',
        context
    )

@user_passes_test(is_admin)
def update_type_course(request, type_course_id):
    type_course = get_object_or_404(Type_Course, pk= type_course_id)
    form_action = reverse('mecip:update_type', args=(type_course_id,))

    if request.method == 'POST':
        form = TypeCourseForm(request.POST, instance=type_course)

        

        if form.is_valid():
            form.save()
            messages.success(request, 'Tipo alterado com sucesso')
            return redirect('mecip:update_type', type_course_id=type_course.id)

        else:
            messages.error(request, 'Erro ao alterar Tipo')
            context = {
            'form': form,
            'form_action': form_action,
            'site_title': 'Editar Tipo',
            }


            return render(
                request,
                'mecip/create.html',
                context
            )

    form = TypeCourseForm(instance=type_course)
    context = {
        'form': form,
        'form_action': form_action,
        'site_title': 'Editar Tipo',
    }
    return render(request, 'mecip/create.html', context)

mecip/views/type_course_view.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from mecip.models import Type_Course

def index_type_course(request):
    type_course = Type_Course.objects \
        .order_by('-id')
    paginator = Paginator(type_course, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Tipos'
    }

    return render(
        request,
        'mecip/index_type_course.html',
        context,
    )

def type_course(request, type_course_id):

    single_type = get_object_or_404(
        Type_Course, pk=type_course_id,
    )


    context = {
        'type_course': single_type,
        'site_title': f'Curso - {single_type.type_name_course}',
    }

    return render(
        request,
        'mecip/type.html',
        context,
    )

mecip/templates/mecip/campus.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ campus.first_name }} {{ campus.last_name }} 
        </h1>
        <p><b>Nome Campus:</b> {{ campus.campus_name }}</p>
        <p><b>Cidade:</b> {{ campus.city }}</p>
        <p><b>Rua:</b> {{ campus.street }}</p>
        <p><b>Numero:</b> {{ campus.number }}</p>
        <p><b>Bairro:</b> {{ campus.neighborhood }}</p>
        <p><b>Numero de Contato:</b> {{ campus.contact_number }}</p>
        <p><b>E-mail:</b> {{ campus.email_campus }}</p>
        <p><b>Created Date:</b> {{ campus.created_date }}</p>

        {% if user.is_superuser %}
            <div class="campus-links">
                <a class="btn btn-link" href="{% url "mecip:update" campus.id %}">Editar</a>
            </div>
        {% endif %}
    </div>
{% endblock content %}

mecip/templates/mecip/course.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ course.type_course }}
        </h1>
        <p><b>Nome Curso:</b> {{ course.type_course }}</p>
        <p><b>Descrição do Curso:</b> {{ course.description }}</p>
        <p><b>Campus:</b> {{ course.campus.campus_name }}</p>
        <p><b>Cidade:</b> {{ course.campus.city }}</p>

        {% if user.is_superuser %}
            <div class="contact-links">
                <a class="btn btn-link" href="{% url "mecip:update_course" course_id=course.id %}">Editar</a>
                <a class="btn btn-link" href="{% url 'mecip:campus' campus_id=course.campus.id %}">Campus</a>

                {% if report %}
                    <a class="btn btn-link" href="{% url 'mecip:report' report.id %}">Relatório</a>
                {% else %}
                    <a class="btn btn-primary" href="{% url 'mecip:create_report_params' course_id=course.id campus_id=course.campus.id%}">Criar Relatório</a>
                {% endif %}
            </div>
            
        {% endif %}
    </div>
{% endblock %}

mecip/templates/mecip/create.html
{% extends "global/base.html" %}

{% block content  %}
    <div class="form-wrapper">


        <h2>{{ site_title }}</h2>

        <form 
        action= '{{ form_action }}'
        method="POST"
        enctype="multipart/form-data"
        >
        {% csrf_token %}

        <div class="form-content">
            {% for field in form  %}
                <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {{ field.errors }}
                </div>
            {% endfor %}

            
        </div>

        <div class="form-content">
            <div class="form-group">
            <button class="btn" type="submit">Enviar</button>
            </div>
        </div>

        </form>
    </div>
{% endblock content  %}

mecip/templates/mecip/index.html
{% extends "global/base.html" %}


{% block content %}
{% if page_obj %}
    <div class="responsive_table">
        <table class="contacts-table">
            <caption class="table-caption">
                Campus
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">Campus</th>
                    <th class="table-header">Cidade</th>
                    <th class="table-header">Rua</th>
                    <th class="table-header">Numero</th>
                    <th class="table-header">Bairro</th>
                    <th class="table-header">E-mail Campus</th>
                    <th class="table-header">Numero Contato</th>
                </tr>
            </thead>

            <tbody>
                {% for camp in page_obj  %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" 
                            href="{% url "mecip:campus" camp.id %}">
                                {{ camp.campus_name }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="#">
                                {{ camp.city }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="#">
                                {{ camp.street }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="#">
                                {{ camp.number }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="#">
                                {{ camp.neighborhood }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="#">
                                {{ camp.email_campus }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="#">
                                {{ camp.contact_number }}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% else %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum Campus encontrado.
        </h1>
    </div>
{% endif %}
{% endblock content %}
    

mecip/templates/mecip/index_course.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
    <div class="responsive_table">
        <table class="contacts-table">
            <caption class="table-caption">
                Cursos
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">Nome Curso</th>
                    <th class="table-header">Descrição</th>
                    <th class="table-header">Campus</th>
                    <th class="table-header">Cidade</th>
                </tr>
            </thead>

            <tbody>
                {% for course in page_obj  %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" 
                            href="{% url "mecip:course" course.id %}">
                                {{ course.type_course }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="{% url "mecip:course" course.id %}">
                                {{ course.description }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="{% url "mecip:course" course.id %}">
                                {{ course.campus.campus_name }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="{% url "mecip:course" course.id %}">
                                {{ course.campus.city }}
                            </a>                            
                        </td>
                    </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% else %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum Campus encontrado.
        </h1>
    </div>
{% endif %}
{% endblock content %}
    

mecip/templates/mecip/index_report.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
    <div class="responsive_table">
        <table class="contacts-table">
            <caption class="table-caption">
                Relatórios
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">Nome Curso</th>
                    <th class="table-header">Campus</th>
                    <th class="table-header">Cidade</th>
                </tr>
            </thead>

            <tbody>
                {% for report in page_obj  %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" href="{% url "mecip:report" report.id %}">
                                {{ report.course.type_course }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="{% url "mecip:report" report.id %}">
                                {{ report.campus.campus_name }}
                            </a>
                        </td>                      
                        <td class="table-cel">
                            <a class="table-link" href="{% url "mecip:report" report.id %}">
                                {{ report.campus.city }}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% else %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum Relatorio encontrado.
        </h1>
    </div>
{% endif %}
{% endblock content %}
    

mecip/templates/mecip/index_type_course.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
    <div class="responsive_table">
        <table class="contacts-table">
            <caption class="table-caption">
                Tipos de Cursos
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">Nome do Curso</th>
                    <th class="table-header">Duração em Semestre</th>
                    <th class="table-header">Nivel do Curso</th>
                </tr>
            </thead>

            <tbody>
                {% for type_course in page_obj  %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" 
                            href="{% url "mecip:type_course" type_course.id %}">
                                {{ type_course.type_name_course }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="{% url "mecip:type_course" type_course.id %}">
                                {{ type_course.duration }}
                            </a>
                        </td>
                        <td class="table-cel">
                            <a class="table-link" href="{% url "mecip:type_course" type_course.id %}">
                                {{ type_course.type_categorie.categorie }}
                            </a>
                        </td>

                    </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% else %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum Campus encontrado.
        </h1>
    </div>
{% endif %}
{% endblock content %}
    

mecip/templates/mecip/login.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="style-login">

    <h2 class="mecip-text">MECIP</h2>
    <h2>Entrar</h2>

    {% include "mecip/partials/_user-form.html" %}
    
  </div>
{% endblock content %}

mecip/templates/mecip/register.html
{% extends "global/base.html" %}

{% block content  %}
    <div class="style-login">

        <h2 class="mecip-text">MECIP</h2>
        <h2>Registro</h2>

        <form 
        action= '{{ form_action }}'
        method="POST"
        >
        {% csrf_token %}

        <div class="form-content">
            {% for field in form  %}
                <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {{ field.errors }}
                </div>
            {% endfor %}

            
        </div>

        <div class="form-content">
            <div class="form-group">
            <button class="btn" type="submit">Criar</button>
            <a href=" {% url "mecip:login" %}">Entrar</a>
            </div>
        </div>

        </form>
    </div>
{% endblock content  %}

mecip/templates/mecip/report.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <caption class="table-caption">
            <h1>Relatorio:</h1>
        </caption>
        <h1 class="single-contact-name">
            {{ report.course.type_course }}
        </h1>
        <p><b>Nome Curso:</b> {{ report.course.type_course }}</p>
        <p><b>Avaliação:</b> {{ report.assessment }}</p>
        <p><b>Campus:</b> {{ report.campus.campus_name }}
        <p><b>Cidade:</b> {{ report.campus.city }}

        {% if user.is_superuser %}
            <div class="contact-links">
                <a class="btn btn-link" href="{% url "mecip:update_report" report_id=report.id %}">Editar</a>
                <a class="btn btn-link" href="{% url "mecip:campus" report.campus.id  %}">Campus</a>
                <a class="btn btn-link" href="{% url "mecip:course" report.course.id  %}">Curso</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

mecip/templates/mecip/type.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ type_course.type_name_course }}
        </h1>
        <p><b>Nome do Curso:</b> {{ type_course.type_name_course }}</p>
        <p><b>Duração do Curso em Semestres:</b> {{ type_course.duration }}</p>
        <p><b>Nível:</b> {{ type_course.type_categorie.categorie }} </p>

        {% if user.is_superuser %}
            <div class="contact-links">
                <a class="btn btn-link" href="{% url "mecip:update_type" type_course_id=type_course.id %}">Editar</a>
            </div>
            
        {% endif %}

    </div>
{% endblock %}